CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE entries(
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  entry TEXT NOT NULL,
  category TEXT NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
