CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE entries(
  id SERIAL PRIMARY KEY, 
  title TEXT, 
  entry TEXT, 
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  edited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
