name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: "verify db"
        run: |
          apt-get update
          apt-get install -y postgresql-14
          PGPASSWORD=password psql -U postgres -h postgres -c "select * from pg_database"
      # - run: npm install
      # - run: npm run client-install
      # - run: npm run server-install
      # - run: npm run migrate-db ci
      # - run: npm run server-build
